name: Publish Docker image

on: [push]

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v2.0
      - name: set kubernetes context
        uses: azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_API }}
          k8s-secret: ${{ secrets.SA_TOKEN }}
        id: setcontext

      - uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
              yaml/deployment.yaml